# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Electronic-Eng', 'Electronic-Eng'), ('Start-up', 'Start-up'), ('Project', 'Project'), ('Experience', 'Experience')], default=False, max_length=100)),
                ('photo1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/photo1/%Y/%M/%D')),
                ('photo2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/photo2/%Y/%M/%D')),
                ('summary', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
