# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170427_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='blog/photo1/%Y/%M/%D'),
        ),
    ]
