# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170503_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='blog/photo2/%Y/%M/%D'),
        ),
    ]
