# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170503_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='period',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
